# Generated by Django 3.2.25 on 2024-11-03 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('acompanhamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acompanhamento',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('funcionario_id', models.CharField(max_length=255, unique=True)),
                ('curso_id', models.CharField(max_length=255, unique=True)),
                ('tempo_no_sistema', models.IntegerField()),
                ('progresso', models.IntegerField()),
                ('tempo_falta', models.IntegerField()),
            ],
            options={
                'ordering': ['username'],
            },
        ),
    ]
