# Generated by Django 3.2.25 on 2024-11-03 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='certificado',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('nome', models.CharField(max_length=255, unique=True)),
                ('assinatura_Digital', models.CharField(max_length=255)),
                ('id_curso_pertencente', models.CharField(max_length=255)),
                ('empresa_pertencente', models.CharField(max_length=255)),
                ('id_empresa_pertencente', models.CharField(max_length=255)),
                ('id_adm_responsavel', models.CharField(max_length=255)),
                ('adm_responsavel', models.CharField(max_length=255)),
                ('id_funcionario', models.CharField(max_length=255)),
                ('data_emissao', models.DateField()),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], max_length=50)),
            ],
        ),
    ]
