# Generated by Django 3.2.25 on 2024-11-03 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
                ('empresa_pertencente', models.CharField(max_length=255)),
                ('id_empresa_pertencente', models.CharField(max_length=255)),
                ('midia_intoduction', models.FileField(upload_to='midias/')),
                ('id_ref_MIDIA', models.CharField(max_length=255)),
                ('progress', models.IntegerField()),
            ],
        ),
    ]
