# Generated by Django 3.2.25 on 2024-11-03 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('curso_pertencente', models.CharField(max_length=255)),
                ('id_curso_pertencente', models.CharField(max_length=255)),
                ('midia', models.BinaryField()),
            ],
        ),
    ]
